name = "stompguard-site"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "SG_CACHE"
id = "37eb1de293e645c3901db21e52523b12"

[[kv_namespaces]]
binding = "SG_SESSIONS"
id = "00856e872402439ba96d67c61bdb2aec"

[[d1_databases]]
binding = "DB"
database_name = "stompguard-orders"
database_id = "81a44b53-a595-49b3-a8a9-1e551a3d1701"
